# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datum_pb2 as datum__pb2
from . import subject_pb2 as subject__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aggregate.proto',
  package='kaist.iclab.abclogger',
  syntax='proto3',
  serialized_options=b'\n kaist.iclab.abclogger.grpc.protoB\021AggregationProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ggregate.proto\x12\x15kaist.iclab.abclogger\x1a\x0b\x64\x61tum.proto\x1a\rsubject.proto\"\xf7\x01\n\x0b\x41ggregation\x12\x37\n\x05group\x18\x01 \x03(\x0b\x32(.kaist.iclab.abclogger.Aggregation.Group\x1a\xae\x01\n\x05Group\x12\x34\n\ndatum_type\x18\x01 \x01(\x0e\x32 .kaist.iclab.abclogger.DatumType\x12/\n\x07subject\x18\x02 \x01(\x0b\x32\x1e.kaist.iclab.abclogger.Subject\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x17\n\x0f\x66irst_timestamp\x18\x04 \x01(\x03\x12\x16\n\x0elast_timestamp\x18\x05 \x01(\x03\x42\x35\n kaist.iclab.abclogger.grpc.protoB\x11\x41ggregationProtosb\x06proto3'
  ,
  dependencies=[datum__pb2.DESCRIPTOR,subject__pb2.DESCRIPTOR,])




_AGGREGATION_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='kaist.iclab.abclogger.Aggregation.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datum_type', full_name='kaist.iclab.abclogger.Aggregation.Group.datum_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='kaist.iclab.abclogger.Aggregation.Group.subject', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kaist.iclab.abclogger.Aggregation.Group.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_timestamp', full_name='kaist.iclab.abclogger.Aggregation.Group.first_timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_timestamp', full_name='kaist.iclab.abclogger.Aggregation.Group.last_timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=318,
)

_AGGREGATION = _descriptor.Descriptor(
  name='Aggregation',
  full_name='kaist.iclab.abclogger.Aggregation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='kaist.iclab.abclogger.Aggregation.group', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AGGREGATION_GROUP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=318,
)

_AGGREGATION_GROUP.fields_by_name['datum_type'].enum_type = datum__pb2._DATUMTYPE
_AGGREGATION_GROUP.fields_by_name['subject'].message_type = subject__pb2._SUBJECT
_AGGREGATION_GROUP.containing_type = _AGGREGATION
_AGGREGATION.fields_by_name['group'].message_type = _AGGREGATION_GROUP
DESCRIPTOR.message_types_by_name['Aggregation'] = _AGGREGATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Aggregation = _reflection.GeneratedProtocolMessageType('Aggregation', (_message.Message,), {

  'Group' : _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), {
    'DESCRIPTOR' : _AGGREGATION_GROUP,
    '__module__' : 'aggregate_pb2'
    # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.Aggregation.Group)
    })
  ,
  'DESCRIPTOR' : _AGGREGATION,
  '__module__' : 'aggregate_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.Aggregation)
  })
_sym_db.RegisterMessage(Aggregation)
_sym_db.RegisterMessage(Aggregation.Group)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
