# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart_beat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datum_pb2 as datum__pb2
from . import subject_pb2 as subject__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='heart_beat.proto',
  package='kaist.iclab.abclogger',
  syntax='proto3',
  serialized_options=b'\n kaist.iclab.abclogger.grpc.protoB\017HeartBeatProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10heart_beat.proto\x12\x15kaist.iclab.abclogger\x1a\x0b\x64\x61tum.proto\x1a\rsubject.proto\"\x9f\x01\n\tHeartBeat\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x16\n\x0eutc_offset_sec\x18\x02 \x01(\x05\x12/\n\x07subject\x18\x03 \x01(\x0b\x32\x1e.kaist.iclab.abclogger.Subject\x12\x36\n\x0b\x64\x61ta_status\x18\x04 \x03(\x0b\x32!.kaist.iclab.abclogger.DataStatus\"\x82\x03\n\nDataStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0equalified_name\x18\x02 \x01(\t\x12\x34\n\ndatum_type\x18\x03 \x01(\x0e\x32 .kaist.iclab.abclogger.DatumType\x12\x16\n\x0eturned_on_time\x18\x04 \x01(\x03\x12\x19\n\x11last_time_written\x18\x05 \x01(\x03\x12\x19\n\x11records_collected\x18\x06 \x01(\x03\x12\x18\n\x10records_uploaded\x18\x07 \x01(\x03\x12\x33\n\toperation\x18\x08 \x01(\x0e\x32 .kaist.iclab.abclogger.Operation\x12\r\n\x05\x65rror\x18\t \x01(\t\x12=\n\x06others\x18\n \x03(\x0b\x32-.kaist.iclab.abclogger.DataStatus.OthersEntry\x1a-\n\x0bOthersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\'\n\tOperation\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42\x33\n kaist.iclab.abclogger.grpc.protoB\x0fHeartBeatProtosb\x06proto3'
  ,
  dependencies=[datum__pb2.DESCRIPTOR,subject__pb2.DESCRIPTOR,])

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='kaist.iclab.abclogger.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=622,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
OFF = 0
ON = 1
ERROR = 2



_HEARTBEAT = _descriptor.Descriptor(
  name='HeartBeat',
  full_name='kaist.iclab.abclogger.HeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='kaist.iclab.abclogger.HeartBeat.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utc_offset_sec', full_name='kaist.iclab.abclogger.HeartBeat.utc_offset_sec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='kaist.iclab.abclogger.HeartBeat.subject', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_status', full_name='kaist.iclab.abclogger.HeartBeat.data_status', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=231,
)


_DATASTATUS_OTHERSENTRY = _descriptor.Descriptor(
  name='OthersEntry',
  full_name='kaist.iclab.abclogger.DataStatus.OthersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kaist.iclab.abclogger.DataStatus.OthersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kaist.iclab.abclogger.DataStatus.OthersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=620,
)

_DATASTATUS = _descriptor.Descriptor(
  name='DataStatus',
  full_name='kaist.iclab.abclogger.DataStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kaist.iclab.abclogger.DataStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qualified_name', full_name='kaist.iclab.abclogger.DataStatus.qualified_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datum_type', full_name='kaist.iclab.abclogger.DataStatus.datum_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turned_on_time', full_name='kaist.iclab.abclogger.DataStatus.turned_on_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_time_written', full_name='kaist.iclab.abclogger.DataStatus.last_time_written', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='records_collected', full_name='kaist.iclab.abclogger.DataStatus.records_collected', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='records_uploaded', full_name='kaist.iclab.abclogger.DataStatus.records_uploaded', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='kaist.iclab.abclogger.DataStatus.operation', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='kaist.iclab.abclogger.DataStatus.error', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='others', full_name='kaist.iclab.abclogger.DataStatus.others', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DATASTATUS_OTHERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=620,
)

_HEARTBEAT.fields_by_name['subject'].message_type = subject__pb2._SUBJECT
_HEARTBEAT.fields_by_name['data_status'].message_type = _DATASTATUS
_DATASTATUS_OTHERSENTRY.containing_type = _DATASTATUS
_DATASTATUS.fields_by_name['datum_type'].enum_type = datum__pb2._DATUMTYPE
_DATASTATUS.fields_by_name['operation'].enum_type = _OPERATION
_DATASTATUS.fields_by_name['others'].message_type = _DATASTATUS_OTHERSENTRY
DESCRIPTOR.message_types_by_name['HeartBeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['DataStatus'] = _DATASTATUS
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'heart_beat_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)

DataStatus = _reflection.GeneratedProtocolMessageType('DataStatus', (_message.Message,), {

  'OthersEntry' : _reflection.GeneratedProtocolMessageType('OthersEntry', (_message.Message,), {
    'DESCRIPTOR' : _DATASTATUS_OTHERSENTRY,
    '__module__' : 'heart_beat_pb2'
    # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.DataStatus.OthersEntry)
    })
  ,
  'DESCRIPTOR' : _DATASTATUS,
  '__module__' : 'heart_beat_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.DataStatus)
  })
_sym_db.RegisterMessage(DataStatus)
_sym_db.RegisterMessage(DataStatus.OthersEntry)


DESCRIPTOR._options = None
_DATASTATUS_OTHERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
