# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hqs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hqs.proto',
  package='kaist.iclab.abclogger',
  syntax='proto3',
  serialized_options=b'\n kaist.iclab.abclogger.grpc.protoB\tHqsProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\thqs.proto\x12\x15kaist.iclab.abclogger\"\x84\x01\n\tStatistic\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x0f\n\x07std_dev\x18\x02 \x01(\x01\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x12\x0e\n\x06median\x18\x05 \x01(\x01\x12\x16\n\x0elower_quartile\x18\x06 \x01(\x01\x12\x16\n\x0eupper_quartile\x18\x07 \x01(\x01\"b\n\x03Hqs\x12\x33\n\tstatistic\x18\x01 \x01(\x0b\x32 .kaist.iclab.abclogger.Statistic\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x17\n\x0frank_percentile\x18\x03 \x01(\x05\"\x85\x02\n\x0bPhysicalHqs\x12\x33\n\x0f\x61\x63tive_duration\x18\x01 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12\x35\n\x11inactive_duration\x18\x02 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12.\n\nstep_count\x18\x03 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12,\n\x08\x64istance\x18\x04 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12,\n\x08\x63\x61lories\x18\x05 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\"\xaa\x01\n\tSocialHqs\x12\x31\n\rcall_duration\x18\x01 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12\x31\n\rmessage_count\x18\x02 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12\x37\n\x13social_app_duration\x18\x03 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\"\xae\x02\n\nDigitalHqs\x12=\n\tapp_usage\x18\x01 \x03(\x0b\x32*.kaist.iclab.abclogger.DigitalHqs.AppUsage\x12.\n\ndata_usage\x18\x02 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12\x38\n\x14phone_usage_duration\x18\x03 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x12/\n\x0bmedia_taken\x18\x04 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.Hqs\x1a\x46\n\x08\x41ppUsage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12,\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x1a.kaist.iclab.abclogger.HqsB-\n kaist.iclab.abclogger.grpc.protoB\tHqsProtosb\x06proto3'
)




_STATISTIC = _descriptor.Descriptor(
  name='Statistic',
  full_name='kaist.iclab.abclogger.Statistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='kaist.iclab.abclogger.Statistic.mean', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='std_dev', full_name='kaist.iclab.abclogger.Statistic.std_dev', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='kaist.iclab.abclogger.Statistic.min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='kaist.iclab.abclogger.Statistic.max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='median', full_name='kaist.iclab.abclogger.Statistic.median', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_quartile', full_name='kaist.iclab.abclogger.Statistic.lower_quartile', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_quartile', full_name='kaist.iclab.abclogger.Statistic.upper_quartile', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=169,
)


_HQS = _descriptor.Descriptor(
  name='Hqs',
  full_name='kaist.iclab.abclogger.Hqs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statistic', full_name='kaist.iclab.abclogger.Hqs.statistic', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kaist.iclab.abclogger.Hqs.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank_percentile', full_name='kaist.iclab.abclogger.Hqs.rank_percentile', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=269,
)


_PHYSICALHQS = _descriptor.Descriptor(
  name='PhysicalHqs',
  full_name='kaist.iclab.abclogger.PhysicalHqs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='active_duration', full_name='kaist.iclab.abclogger.PhysicalHqs.active_duration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inactive_duration', full_name='kaist.iclab.abclogger.PhysicalHqs.inactive_duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step_count', full_name='kaist.iclab.abclogger.PhysicalHqs.step_count', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='kaist.iclab.abclogger.PhysicalHqs.distance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calories', full_name='kaist.iclab.abclogger.PhysicalHqs.calories', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=533,
)


_SOCIALHQS = _descriptor.Descriptor(
  name='SocialHqs',
  full_name='kaist.iclab.abclogger.SocialHqs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_duration', full_name='kaist.iclab.abclogger.SocialHqs.call_duration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_count', full_name='kaist.iclab.abclogger.SocialHqs.message_count', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='social_app_duration', full_name='kaist.iclab.abclogger.SocialHqs.social_app_duration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=706,
)


_DIGITALHQS_APPUSAGE = _descriptor.Descriptor(
  name='AppUsage',
  full_name='kaist.iclab.abclogger.DigitalHqs.AppUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kaist.iclab.abclogger.DigitalHqs.AppUsage.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='kaist.iclab.abclogger.DigitalHqs.AppUsage.duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=941,
  serialized_end=1011,
)

_DIGITALHQS = _descriptor.Descriptor(
  name='DigitalHqs',
  full_name='kaist.iclab.abclogger.DigitalHqs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_usage', full_name='kaist.iclab.abclogger.DigitalHqs.app_usage', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_usage', full_name='kaist.iclab.abclogger.DigitalHqs.data_usage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_usage_duration', full_name='kaist.iclab.abclogger.DigitalHqs.phone_usage_duration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='media_taken', full_name='kaist.iclab.abclogger.DigitalHqs.media_taken', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DIGITALHQS_APPUSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=1011,
)

_HQS.fields_by_name['statistic'].message_type = _STATISTIC
_PHYSICALHQS.fields_by_name['active_duration'].message_type = _HQS
_PHYSICALHQS.fields_by_name['inactive_duration'].message_type = _HQS
_PHYSICALHQS.fields_by_name['step_count'].message_type = _HQS
_PHYSICALHQS.fields_by_name['distance'].message_type = _HQS
_PHYSICALHQS.fields_by_name['calories'].message_type = _HQS
_SOCIALHQS.fields_by_name['call_duration'].message_type = _HQS
_SOCIALHQS.fields_by_name['message_count'].message_type = _HQS
_SOCIALHQS.fields_by_name['social_app_duration'].message_type = _HQS
_DIGITALHQS_APPUSAGE.fields_by_name['duration'].message_type = _HQS
_DIGITALHQS_APPUSAGE.containing_type = _DIGITALHQS
_DIGITALHQS.fields_by_name['app_usage'].message_type = _DIGITALHQS_APPUSAGE
_DIGITALHQS.fields_by_name['data_usage'].message_type = _HQS
_DIGITALHQS.fields_by_name['phone_usage_duration'].message_type = _HQS
_DIGITALHQS.fields_by_name['media_taken'].message_type = _HQS
DESCRIPTOR.message_types_by_name['Statistic'] = _STATISTIC
DESCRIPTOR.message_types_by_name['Hqs'] = _HQS
DESCRIPTOR.message_types_by_name['PhysicalHqs'] = _PHYSICALHQS
DESCRIPTOR.message_types_by_name['SocialHqs'] = _SOCIALHQS
DESCRIPTOR.message_types_by_name['DigitalHqs'] = _DIGITALHQS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Statistic = _reflection.GeneratedProtocolMessageType('Statistic', (_message.Message,), {
  'DESCRIPTOR' : _STATISTIC,
  '__module__' : 'hqs_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.Statistic)
  })
_sym_db.RegisterMessage(Statistic)

Hqs = _reflection.GeneratedProtocolMessageType('Hqs', (_message.Message,), {
  'DESCRIPTOR' : _HQS,
  '__module__' : 'hqs_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.Hqs)
  })
_sym_db.RegisterMessage(Hqs)

PhysicalHqs = _reflection.GeneratedProtocolMessageType('PhysicalHqs', (_message.Message,), {
  'DESCRIPTOR' : _PHYSICALHQS,
  '__module__' : 'hqs_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.PhysicalHqs)
  })
_sym_db.RegisterMessage(PhysicalHqs)

SocialHqs = _reflection.GeneratedProtocolMessageType('SocialHqs', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALHQS,
  '__module__' : 'hqs_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.SocialHqs)
  })
_sym_db.RegisterMessage(SocialHqs)

DigitalHqs = _reflection.GeneratedProtocolMessageType('DigitalHqs', (_message.Message,), {

  'AppUsage' : _reflection.GeneratedProtocolMessageType('AppUsage', (_message.Message,), {
    'DESCRIPTOR' : _DIGITALHQS_APPUSAGE,
    '__module__' : 'hqs_pb2'
    # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.DigitalHqs.AppUsage)
    })
  ,
  'DESCRIPTOR' : _DIGITALHQS,
  '__module__' : 'hqs_pb2'
  # @@protoc_insertion_point(class_scope:kaist.iclab.abclogger.DigitalHqs)
  })
_sym_db.RegisterMessage(DigitalHqs)
_sym_db.RegisterMessage(DigitalHqs.AppUsage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
